alt_configs = ["s10-ringctrl.toml"]

[device]
touch = "/dev/input/event22"
consumer = "/dev/input/event23"

[gesture]
threshold = 40

[mappings]
UP = "key:10W"
DOWN = "key:10S"
LEFT = "key:10A"
RIGHT = "key:10D"
TAP = "mouse:left"
POWER = "key:Escape"
