alt_configs = ["s10-ringctrl.toml"]

[device]
touch = "/dev/input/event22"
consumer = "/dev/input/event23"

[gesture]
threshold = 80

[mappings]
UP = "key:W"
DOWN = "key:S"
LEFT = "key:A"
RIGHT = "key:D"
TAP = "key:Space"
POWER = "key:Escape"
