alt_config = "s10-ringctrl.toml"

[device]
touch = "/dev/input/event22"
consumer = "/dev/input/event23"

[gesture]
threshold = 80

[mappings]
UP = "key:SHIFT+Tab"
DOWN = "key:Tab"
LEFT = "command:hyprctl dispatch workspace e-1"
RIGHT = "command:hyprctl dispatch workspace e+1"
POWER = "key:Escape"
